@startuml

() "Docker"
() HTTP

file "QueryJobCache" {
   [QueryCache]
   [ResultCache]
}

file "Model Store"


node "Model Worker" {
    [Model] <--> [Model Store] : Load Model \nfrom store\ninto memory
    [QueryCache] --> [Model]
    [Model] --> [ResultCache]

}


node "Docker API Service" {
    HTTP ..> [ModelController] : Upload \nor edit models
    HTTP ..> [QueryController] : Query a model
    [QueryController] ==> [Docker] : Create/Ensure\nWorker exists
    [QueryController] --> [QueryCache] : Write Query to \ncache
    [QueryController] --> [Model] : Pass query\nfilepath
    [QueryController] <-- [ResultCache] : Read model \nresult
    [ModelController] ---> [Model Store] : Write out the model\n binaries(CSV and RDS)
    [ModelController] --> [Model Database] : Create/Update models
}

database "Model Database" {
    [Table] --> [Model Store]
}
@enduml