"""empty message

Revision ID: 7d4c7414c89e
Revises: 
Create Date: 2019-05-16 12:35:09.965531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.engine import reflection

revision = '7d4c7414c89e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    engine = op.get_bind().engine
    table_names = sa.inspect(engine).get_table_names()
    if 'pathogen_model' not in table_names:
        op.create_table('pathogen_model',
                        sa.Column('id', sa.VARCHAR(), nullable=False, primary_key=True),
                        sa.Column('name', sa.VARCHAR(), nullable=True),
                        sa.Column('query_str', sa.VARCHAR(), nullable=True),
                        sa.Column('model_type', sa.VARCHAR(), nullable=True),
                        sa.Column('rds_key', sa.VARCHAR(), nullable=True),
                        sa.Column('created', sa.DATETIME(), nullable=False, primary_key=True),
                        sa.PrimaryKeyConstraint('id', 'created')
                        )
    # ### end Alembic commands ###


def downgrade():
    # This is our first so nothing to do after this
    pass
