"""empty message

Revision ID: 7d4c7414c89e
Revises: 
Create Date: 2019-05-16 12:35:09.965531

"""
import datetime
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.engine import reflection



revision = '7d4c7414c89e'
down_revision = None
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    engine = op.get_bind().engine
    table_names = sa.inspect(engine).get_table_names()
    if 'pathogen_model' not in table_names:
        # this was our orginal model
        from seattle_flu_incidence_mapper.models.generic_model import base

        class PathogenModel(base):

            __tablename__ = 'pathogen_model'
            id = sa.Column(sa.String, primary_key=True)
            name = sa.Column(sa.String)
            query_str = sa.Column(sa.String)
            model_type = sa.Column(sa.String)
            rds_key = sa.Column(sa.String)
            created = sa.Column(sa.DateTime, primary_key=True, default=datetime.datetime.utcnow)
        PathogenModel.metadata.create_all(engine)
    # ### end Alembic commands ###


def downgrade():
    # This is our first so nothing to do after this
    pass
